# Generated by Django 2.2.2 on 2019-06-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190610_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Info',
        ),
    ]
