# Generated by Django 2.2.2 on 2019-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='designation_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
