# Generated by Django 2.2.2 on 2019-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190619_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email_facebook',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='email_google',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='email_linkd',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='email_twitter',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_work',
            field=models.CharField(default='hello', max_length=500),
        ),
    ]
