# Generated by Django 2.2.2 on 2019-06-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190619_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_head', models.TextField()),
                ('about_dis', models.TextField()),
                ('services_head', models.TextField()),
                ('services_dis', models.TextField()),
                ('portfolio_head', models.TextField()),
                ('team_head', models.TextField()),
                ('team_dis', models.TextField()),
                ('client_head', models.TextField()),
                ('client_dis', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='email_facebook',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_google',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_linkd',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_twitter',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_work',
            field=models.CharField(default='hello', max_length=500),
        ),
    ]
