# Generated by Django 2.2.2 on 2019-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_team_team_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about_dis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='index',
            name='about_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='client_dis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='index',
            name='client_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='portfolio_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='services_dis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='index',
            name='services_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='team_dis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='index',
            name='team_head',
            field=models.CharField(max_length=50),
        ),
    ]
