# Generated by Django 2.2.2 on 2019-06-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190620_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
