# Generated by Django 2.2.2 on 2019-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190620_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_head', models.CharField(max_length=50)),
                ('about_dis', models.CharField(max_length=500)),
                ('services_head', models.CharField(max_length=50)),
                ('services_dis', models.CharField(max_length=500)),
                ('portfolio_head', models.CharField(max_length=50)),
                ('team_head', models.CharField(max_length=50)),
                ('team_dis', models.CharField(max_length=500)),
                ('client_head', models.CharField(max_length=50)),
                ('client_dis', models.CharField(max_length=500)),
            ],
        ),
    ]
