# Generated by Django 2.2.2 on 2019-06-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='contact_head',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='testimonials_head',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='why_dis',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='why_head',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
