# Generated by Django 2.2.2 on 2019-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_testo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testo',
            name='image',
            field=models.ImageField(default=1, upload_to='testimonial/'),
            preserve_default=False,
        ),
    ]
