# Generated by Django 2.2.2 on 2019-06-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_port_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='porduct_name',
            new_name='poduct_name',
        ),
    ]
