# Generated by Django 2.2.2 on 2019-06-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190620_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='produt_name',
        ),
    ]
