# Generated by Django 2.2.2 on 2019-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_product_produt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=50)),
                ('card_dis', models.TextField()),
                ('card_link', models.URLField()),
            ],
        ),
    ]
