# Generated by Django 2.2.2 on 2019-06-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_toggle', models.IntegerField()),
                ('project_toggle', models.IntegerField()),
                ('hours_toggle', models.IntegerField()),
                ('workers_toggle', models.IntegerField()),
            ],
        ),
    ]
