# Generated by Django 2.2.2 on 2019-06-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='select_icon',
            field=models.CharField(choices=[('ion-ios-analytics-outline', 'ion-ios-analytics-outline'), ('ion-ios-bookmarks-outline', 'ion-ios-bookmarks-outline'), ('ion-ios-paper-outline', 'ion-ios-paper-outline'), ('ion-ios-speedometer-outline', 'ion-ios-speedometer-outline'), ('ion-ios-world-outline', 'ion-ios-world-outline'), ('ion-ios-clock-outline', 'ion-ios-clock-outline')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
