# Generated by Django 2.2.2 on 2019-06-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_service_select_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='why',
            name='card_icon',
            field=models.CharField(choices=[('fa fa-diamond', 'fa fa-diamond'), ('fa fa-language', 'fa fa-language'), ('fa fa-object-group', 'fa fa-object-group')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
