# Generated by Django 2.2.2 on 2019-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_why_card_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_discription', models.TextField()),
                ('About_icon', models.CharField(choices=[('fa fa-shopping-bag', 'Shopping Bag'), ('fa fa-photo', 'Photo'), ('fa fa-bar-chart', 'Bar Chart')], max_length=50)),
                ('About_title', models.CharField(max_length=50)),
                ('About_discrip', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='select_icon',
            field=models.CharField(choices=[('ion-ios-analytics-outline', 'Analytics Outline Icon'), ('ion-ios-bookmarks-outline', 'Bookmarks Outline Icon'), ('ion-ios-paper-outline', 'Paper Outline Icon'), ('ion-ios-speedometer-outline', 'Speedometer Outline Icon'), ('ion-ios-world-outline', 'World Outline Icon'), ('ion-ios-clock-outline', 'Clock Outline Icon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='why',
            name='card_icon',
            field=models.CharField(choices=[('fa fa-diamond', 'Diamond Icon'), ('fa fa-language', 'Language Icon'), ('fa fa-object-group', 'Object Group Icon')], max_length=50),
        ),
    ]
