# Generated by Django 2.2.2 on 2019-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20190621_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutdis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('more_discription', models.TextField()),
            ],
        ),
    ]
