# Generated by Django 2.2.2 on 2019-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_aboutdis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdis',
            name='clas',
            field=models.CharField(choices=[('col-lg-6 wow fadeInUp', 'left'), ('col-lg-6 wow fadeInUp order-1 order-lg-2', 'right')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
