# Generated by Django 2.2.2 on 2019-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_aboutdis_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdis',
            name='div_clas',
            field=models.CharField(choices=[('col-lg-6 wow fadeInUp pt-5 pt-lg-0', 'left'), ('col-lg-6 wow fadeInUp pt-4 pt-lg-0 order-2 order-lg-1', 'right')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
