# Generated by Django 2.2.2 on 2019-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_remove_aboutinfo_about_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='About_discrip',
            new_name='About_discrip1',
        ),
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='About_title',
            new_name='About_title1',
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='About_discrip2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='About_discrip3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='About_title2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='About_title3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='abouts/'),
            preserve_default=False,
        ),
    ]
