# Generated by Django 2.2.2 on 2019-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20190621_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('foot_discription', models.TextField()),
                ('link_head', models.CharField(max_length=50)),
                ('link1', models.CharField(max_length=50)),
                ('link2', models.CharField(max_length=50)),
                ('link3', models.CharField(max_length=50)),
                ('link4', models.CharField(max_length=50)),
                ('link5', models.CharField(max_length=50)),
                ('contacthead', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('news_head', models.TextField()),
                ('news_discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
