# Generated by Django 2.2.2 on 2019-06-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_foot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foot',
            new_name='Newsletter',
        ),
    ]
