# Generated by Django 2.2.2 on 2019-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20190624_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='copy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='designed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='rights',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='strong_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='ulink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='ulink_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
