# Generated by Django 2.2.2 on 2019-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20190624_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
