# Generated by Django 2.2.2 on 2019-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
